spring:
  application:
    name: transactions-integration-test
  datasource:
    url: jdbc:h2:mem:integration-test-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    property-naming-strategy: SNAKE_CASE